version: '3.1'

services:
  database:
    image: postgres:16
    container_name: rust_postgres_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=test
    volumes:
      - postgres_backup:/var/lib/postgresql/data
    ports:
      - "5450:5432"

volumes:
  postgres_backup: